services:
  - type: web
    name: java-springboot-app
    runtime: docker
    repo: https://github.com/adiisunlay/Java-with-SpringBoot
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
