services:
  - type: web
    name: java-springboot-app
    runtime: docker
    repo: https://github.com/adiisunlay/Java-with-SpringBoot
    branch: main
    dockerfilePath: ./Dockerfile
    plan: starter
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DATABASE_URL
        fromDatabase:
          name: your-database-name
          property: connectionString

databases:
  - name: mydb
    databaseName: mydb
    user: admin
    plan: starter-plus                
    ipAllowList:
      - source: 0.0.0.0/0
        description: allow all
